/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Generador.java
 *
 * Created on 28-sep-2013, 17:54:25
 */
package Formularios;

import Clases.Conectar;
import Clases.GenerarNumeros;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.*;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
//import org.hsqldb.Column;

/**
 *
 * @author Administrador
 */
public class Generador extends javax.swing.JFrame {
 

    /** Creates new form Generador */
    public Generador() {
        initComponents();
          bloquear();
        numeros();
        cargar();
         
    }
    void limpiar(){
        txtdes.setText(null);
        txtpre.setText(null);
    }
    
    void numeros()
     {
        int j;
    
        String c="";
       // String SQL="select count(*) from productos";
        String SQL="SELECT MAX(cod_pro) AS cod_pro FROM productos";
        //String SQL="SELECT @@identity AS ID";
        try {
            Statement st = cn.createStatement();
            ResultSet rs=st.executeQuery(SQL);
            if(rs.next())
            {              
                 c=rs.getString("cod_pro");
            }
             System.out.print(c); 
             
             if(c==null)
             {
                 txtcod.setText("CP0001");
             }
             else{
                 char r1 = c.charAt(2);
                 char r2 = c.charAt(3);
                 char r3 = c.charAt(4);
                 char r4 = c.charAt(5);
                 System.out.print(""+r1+r2+r3+r4);
                 String juntar = ""+r1+r2+r3+r4;
                 int var=Integer.parseInt(juntar);
                 System.out.print("\n este lo que vale numericamente"+var);
                 GenerarNumeros gen = new GenerarNumeros();
                 gen.generar(var);
                 
                 txtcod.setText(gen.serie());
                 
             }
            } 
        catch (SQLException ex) 
        {
           Logger.getLogger(IngresoProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   void bloquear()
   {
       txtcod.setEnabled(false);
       txtdes.setEnabled(false);
       txtpre.setEnabled(false);
       btnactualizar.setEnabled(false); 
       btnguardar.setEnabled(false);
       btncancelar.setEnabled(false);
       btnnuevo.setEnabled(true);
   }
   void desbloquear()
   {
       txtcod.setEnabled(false);
       txtdes.setEnabled(true);
       txtpre.setEnabled(true);
       btnactualizar.setEnabled(true); 
       btnguardar.setEnabled(true);
       btncancelar.setEnabled(true);
       btnnuevo.setEnabled(false);
   }
   
   void cargar()
   {
             
        try {
            DefaultTableModel model= new DefaultTableModel();
             model.addColumn("CODIGO");
             model.addColumn("DESCRIPCION");
             model.addColumn("PRECIO");
             model.addColumn("IMAGEN");
             tbpro.setModel(model);
            
             
    
       String consultar="SELECT * FROM productos";
       String []datos= new String[4];
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(consultar);
            while(rs.next())
            {
                datos[0]=rs.getString("cod_pro");
                datos[1]=rs.getString("des_pro");
                datos[2]=rs.getString("pre_pro");
                datos[3]=rs.getString("nomimagen");
                
                model.addRow(datos);
            }
          //  tbpro.setModel(model);
            
        } catch (SQLException ex) {
            Logger.getLogger(IngresoProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   
   }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnmodificar = new javax.swing.JMenuItem();
        mneliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpre = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btnselecionar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtnomimagen = new javax.swing.JTextField();
        lblfoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpro = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jPopupMenu1.setName("jPopupMenu1"); // NOI18N

        mnmodificar.setText("Modificar");
        mnmodificar.setName("mnmodificar"); // NOI18N
        mnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmodificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnmodificar);

        mneliminar.setText("Eliminar");
        mneliminar.setName("mneliminar"); // NOI18N
        mneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mneliminarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mneliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DETALLE PRODUCTO"));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("CODIGO:");
        jLabel1.setName("jLabel1"); // NOI18N

        txtcod.setName("txtcod"); // NOI18N

        jLabel2.setText("DESCRIPCION:");
        jLabel2.setName("jLabel2"); // NOI18N

        txtdes.setName("txtdes"); // NOI18N
        txtdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesActionPerformed(evt);
            }
        });

        jLabel3.setText("PRECIO:");
        jLabel3.setName("jLabel3"); // NOI18N

        txtpre.setName("txtpre"); // NOI18N

        btnnuevo.setText("NUEVO");
        btnnuevo.setName("btnnuevo"); // NOI18N
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnguardar.setText("GUARDAR");
        btnguardar.setName("btnguardar"); // NOI18N
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncancelar.setText("CANCELAR");
        btncancelar.setName("btncancelar"); // NOI18N
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnactualizar.setText("ACTUALIZAR");
        btnactualizar.setName("btnactualizar"); // NOI18N
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnselecionar.setText("Seleccionar");
        btnselecionar.setName("btnselecionar"); // NOI18N
        btnselecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselecionarActionPerformed(evt);
            }
        });

        jLabel4.setText("IMAGEN:");
        jLabel4.setName("jLabel4"); // NOI18N

        txtnomimagen.setName("txtnomimagen"); // NOI18N

        lblfoto.setName("lblfoto"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnnuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnactualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncancelar)
                        .addGap(0, 204, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdes, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(txtpre, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomimagen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnselecionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(lblfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtpre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnomimagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnselecionar)))
                    .addComponent(lblfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnuevo)
                    .addComponent(btnguardar)
                    .addComponent(btnactualizar)
                    .addComponent(btncancelar))
                .addContainerGap())
        );

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tbpro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRIPCION", "PRECIO", "IMAGEN"
            }
        ));
        tbpro.setComponentPopupMenu(jPopupMenu1);
        tbpro.setName("tbpro"); // NOI18N
        tbpro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbproMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbpro);

        jButton1.setText("MOSTRAR");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesActionPerformed
// TODO add your handling code here:
    txtdes.transferFocus();
}//GEN-LAST:event_txtdesActionPerformed

private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
// TODO add your handling code here:
    desbloquear();
    txtdes.requestFocus();
    btnactualizar.setEnabled(false);
    limpiar();
    numeros();
}//GEN-LAST:event_btnnuevoActionPerformed

private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
// TODO add your handling code here:
    
    String insertar="INSERT INTO productos(cod_pro,des_pro,pre_pro,nomimagen,imagen) VALUES (?,?,?,?,?)";
        try {
            // Creamos una variable para poder obtener la cantidad de bytes de una imagen
            FileInputStream  archivofoto;
            PreparedStatement pst = cn.prepareStatement(insertar);
              pst.setString(1, txtcod.getText());
            pst.setString(2, txtdes.getText());
            pst.setString(3, txtpre.getText());
            pst.setString(4, txtnomimagen.getText());
            // pero para ello necesitamos conocer la ruta de la imagen
            archivofoto = new FileInputStream(txtnomimagen.getText());
            //SetBinaryStream permite almacenar cantidad de bytes en la base de datos
            pst.setBinaryStream(5, archivofoto);

            int i=pst.executeUpdate();
            if(i>0){
            JOptionPane.showMessageDialog(null, "Se guardo correctamente");
           }
             bloquear();
            numeros();
            cargar();
            limpiar();
             
               txtnomimagen.setText(null);
               lblfoto.setIcon(null);
        } catch (SQLException ex) {
            Logger.getLogger(IngresoProductos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}//GEN-LAST:event_btnguardarActionPerformed

private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
// TODO add your handling code here:
    bloquear();
}//GEN-LAST:event_btncancelarActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    try {
            
            
            JasperReport reportes=JasperCompileManager.compileReport("reportesProductos.jrxml");
            JasperPrint print=JasperFillManager.fillReport(reportes, null,this.cn);
            JasperViewer.viewReport(print);
            
        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
}//GEN-LAST:event_jButton1ActionPerformed

private void tbproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbproMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_tbproMouseClicked

private void mnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmodificarActionPerformed
// TODO add your handling code here:
   
    int fila = tbpro.getSelectedRow();
  
    if(fila>=0)
    {
     
         desbloquear();
           btnguardar.setEnabled(false);
        String cod=tbpro.getValueAt(fila, 0).toString();
        String des=tbpro.getValueAt(fila, 1).toString();
        String pre=tbpro.getValueAt(fila, 2).toString();
        String img=tbpro.getValueAt(fila, 3).toString();
        txtcod.setText(cod);
        txtdes.setText(des);
        txtpre.setText(pre);      
        txtnomimagen.setText(img);
        Image foto = getToolkit().getImage(img);
        foto= foto.getScaledInstance(110, 110, 1);
        lblfoto.setIcon(new ImageIcon(foto));
     
    }
    else
    {
       JOptionPane.showMessageDialog(null, "Elija una fila...llene la Tabla");
    }
    
}//GEN-LAST:event_mnmodificarActionPerformed

private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
// TODO add your handling code here:
        
       
        try {
            //estas sentencia ya lo explique en insertar datos que esta mas arriba
                    FileInputStream  archivofoto;
        File nombre= new File(txtnomimagen.getText());
        archivofoto = new FileInputStream(nombre);
         String sql="UPDATE productos SET cod_pro = ?, "
                 + "des_pro = ?,"
                 + "pre_pro = ?,"
                 + "nomimagen = ?,"
                 + "imagen=?"
                 + "WHERE cod_pro = '"+txtcod.getText()+"'"; 

            PreparedStatement pst = cn.prepareStatement(sql);
                    pst.setString(1, txtcod.getText());
            pst.setString(2, txtdes.getText());
            pst.setString(3, txtpre.getText());
            pst.setString(4, txtnomimagen.getText());
            archivofoto = new FileInputStream(txtnomimagen.getText());
            pst.setBinaryStream(5, archivofoto);

            int n= pst.executeUpdate();
            if(n>0)
            {
                JOptionPane.showMessageDialog(null, "Datos actualizados con exito");
               bloquear();
               cargar();
               limpiar();
               txtnomimagen.setText(null);
               lblfoto.setIcon(null);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Hubo error en el momento de actualizar los datos");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}//GEN-LAST:event_btnactualizarActionPerformed

private void mneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mneliminarActionPerformed
// TODO add your handling code here:
    int fila=tbpro.getSelectedRow();
    if(fila>-1)
    {
        String cod=tbpro.getValueAt(fila, 0).toString();
        String sqlElim="DELETE FROM productos WHERE cod_pro='"+cod+"'";
            try {
                PreparedStatement pst = cn.prepareStatement(sqlElim);
                int n=pst.executeUpdate();
                if(n>0)
                {
                     JOptionPane.showMessageDialog(null, "Los datos fueron eliminados con exito");
                     cargar();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Hubo Problemas al querer eliminar datos");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Generador.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }
    else
    {
    
    }
}//GEN-LAST:event_mneliminarActionPerformed

    private void btnselecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselecionarActionPerformed
        // TODO add your handling code here:
        //Creamos nuestra variable archivo en la cual podremos usar todos los metodos de la clase jFileChooser
        JFileChooser archivo = new JFileChooser();
        //Si deseamos crear filtros para la selecion de archivos
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;*.JPEG)", "jpg","jpeg");
        //Si deseas que se muestre primero los filtros usa la linea q esta abajo de esta.
        //archivo.setFileFilter(filtro);
        // Agregamos el Filtro pero cuidado se mostrara despues de todos los archivos
        archivo.addChoosableFileFilter(filtro);
        // Colocamos titulo a nuestra ventana de Seleccion
        archivo.setDialogTitle("Abrir Archivo");
        //Si deseamos que muestre una carpeta predetermina usa la siguiente linea
        File ruta = new File("D:/productos");
        //Le implementamos a nuestro ventana de seleccion
         archivo.setCurrentDirectory(ruta);
         //Abrimos nuestra Ventana de Selccion
        int ventana = archivo.showOpenDialog(null);
        //hacemos comparacion en caso de aprete el boton abrir
        if(ventana == JFileChooser.APPROVE_OPTION)
        {
            //Obtenemos la ruta de nuestra imagen seleccionada
            File file = archivo.getSelectedFile();
            //Lo imprimimos en una caja de texto para ver su ruta
            txtnomimagen.setText(String.valueOf(file));
            //de cierto modo necesitamos tener la imagen para ello debemos conocer la ruta de dicha imagen
            Image foto= getToolkit().getImage(txtnomimagen.getText());
            //Le damos dimension a nuestro label que tendra la imagen
            foto= foto.getScaledInstance(110, 110, Image.SCALE_DEFAULT);
            //Imprimimos la imagen en el label
            lblfoto.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_btnselecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Generador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnselecionar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JMenuItem mneliminar;
    private javax.swing.JMenuItem mnmodificar;
    private javax.swing.JTable tbpro;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtnomimagen;
    private javax.swing.JTextField txtpre;
    // End of variables declaration//GEN-END:variables
 Conectar cc= new Conectar();
    Connection cn = cc.conexion();
    
}
