/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;


/**
 *
 * @author marcelo
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    public String cargarCheck(){
        String valor = null;
        
        if(checkFormateo.isSelected()&&checkLimpieza.isSelected()&&checkIntalacion.isSelected()){
            valor="Formateo,Limpieza,Intalacion";
        }else if(checkFormateo.isSelected()&&checkLimpieza.isSelected()){
            valor="Formateo,Limpieza";
        }else if(checkFormateo.isSelected()&&checkIntalacion.isSelected()){
            valor="Formateo,Intalacion";
        }else if(checkLimpieza.isSelected()&&checkIntalacion.isSelected()){
            valor="Limpieza,Intalacion";
        }else if(checkFormateo.isSelected()){
            valor="Formateo";
        }else if(checkLimpieza.isSelected()){
            valor="Limpieza";
        }else if(checkIntalacion.isSelected()){
            valor="Intalacion";
        }
        return valor;
    }
    public void selecionarCheak(String valor){
        if(valor.equals("Formateo,Limpieza,Intalacion")){
            checkFormateo.setSelected(true);
            checkLimpieza.setSelected(true);
            checkIntalacion.setSelected(true);
        }else if(valor.equals("Formateo,Limpieza")){
            checkFormateo.setSelected(true);
            checkLimpieza.setSelected(true);
        }else if(valor.equals("Formateo,Intalacion")){
            checkFormateo.setSelected(true);
            checkIntalacion.setSelected(true);
        }else if(valor.equals("Limpieza,Intalacion")){
            checkLimpieza.setSelected(true);
            checkIntalacion.setSelected(true);
        }else if(valor.equals("Formateo")){
            checkFormateo.setSelected(true);
        }else if(valor.equals("Limpieza")){
            checkLimpieza.setSelected(true);
        }else if(valor.equals("Intalacion")){
            checkIntalacion.setSelected(true);
        }
    }
    public void validarRadioButon(){
        if(radioFormateo.isSelected()){
            System.out.println("Formateo");
        }else if(radioLimpieza.isSelected()){
            System.out.println("Limpieza");
        }else if(radioIntalacion.isSelected()){
            System.out.println("Intalacion");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reparacion = new javax.swing.ButtonGroup();
        checkFormateo = new javax.swing.JCheckBox();
        radioFormateo = new javax.swing.JRadioButton();
        checkLimpieza = new javax.swing.JCheckBox();
        checkIntalacion = new javax.swing.JCheckBox();
        radioLimpieza = new javax.swing.JRadioButton();
        radioIntalacion = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        checkFormateo.setText("Formateo");

        Reparacion.add(radioFormateo);
        radioFormateo.setText("Formateo");

        checkLimpieza.setText("Limpieza");

        checkIntalacion.setText("Intalacion");

        Reparacion.add(radioLimpieza);
        radioLimpieza.setText("Limpieza");

        Reparacion.add(radioIntalacion);
        radioIntalacion.setText("Intalacion");

        jButton1.setText("Validar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkFormateo)
                        .addGap(34, 34, 34)
                        .addComponent(checkLimpieza)
                        .addGap(28, 28, 28)
                        .addComponent(checkIntalacion))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioFormateo)
                                .addGap(18, 18, 18)
                                .addComponent(radioLimpieza)))
                        .addGap(18, 18, 18)
                        .addComponent(radioIntalacion)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkFormateo)
                    .addComponent(checkLimpieza)
                    .addComponent(checkIntalacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioFormateo)
                    .addComponent(radioLimpieza)
                    .addComponent(radioIntalacion))
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        System.out.println(cargarCheck());
//        validarRadioButon();
        selecionarCheak("Intalacion");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Reparacion;
    private javax.swing.JCheckBox checkFormateo;
    private javax.swing.JCheckBox checkIntalacion;
    private javax.swing.JCheckBox checkLimpieza;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton radioFormateo;
    private javax.swing.JRadioButton radioIntalacion;
    private javax.swing.JRadioButton radioLimpieza;
    // End of variables declaration//GEN-END:variables
}
